//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36373
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WD.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class DataAccess : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataAccess defaultInstance = ((DataAccess)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataAccess())));
        
        public static DataAccess Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b4qiff9yzqP7yC4+/FhC3KBDqXIPoKRtZJRRRGcGBoYSGvDyS5jDj+RK28n7C6tPbL9Koi2Wfjs/thzRB" +
            "ETnbGNg8Sx6XguS")]
        public string sql {
            get {
                return ((string)(this["sql"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DLPsoPzwA0vyzEk7DZhQc2gpYnAF2AGks7q0Jig0bwXQUaR04bycZ0xjprGlRkdvUz7PPXnvuZywAhI/t" +
            "+ZvNMy19ZGnNjb4kyQflEMpc0cgt5PFFmlGnD7z3I3hPB3LVjpXdeFVtBSFXK4ozHU2NIWtx+7kfALiz" +
            "8/2WCEClO59Tav6kB11vg==")]
        public string db2 {
            get {
                return ((string)(this["db2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DiLpNYhsJW9O9uKQaD8AwaPcApchhzGYvacSzKIEVQYXXnO5zlBwq5mat20JTqXxDziLqirJf78AlHmzK/nbUC5Y34GijXLBSOCUoVd5Td5iofmFwolgufDNt42EA2BvZZIWon9yYWTxgXGNv0XU+CI9ib/ExwOzB7PSca3By+HZaG62t39LTaIZznJldINW7wyKcBXfXEPkrJync6WP+l1QzkDpFZXOiLmY1GVKIXZFC2pjwX4dYEUJQvyDq+5htpa2V06l76s=")]
        public string oracle {
            get {
                return ((string)(this["oracle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"DiLpNYhsJW9O9uKQaD8AwaPcApchhzGYvacSzKIEVQYXXnO5zlBwq5mat20JTqXxDziLqirJf78AlHmzK/nbUC5Y34GijXLBSOCUoVd5Td5iofmFwolgufDNt42EA2BvZZIWon9yYWTxgXGNv0XU+CI9ib/ExwOzB7PSca3By+HZaG62t39LTaIZznJldINW7wyKcBXfXEPkrJync6WP+l1QzkDpFZXOiLmY1GVKIXZFC2pjwX4dYEUJQvyDq+5htpa2V06l76s=")]
        public string oracle2 {
            get {
                return ((string)(this["oracle2"]));
            }
        }
    }
}
