//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WD.Settings.MCES {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class DataAccess : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataAccess defaultInstance = ((DataAccess)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataAccess())));
        
        public static DataAccess Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YjmsIRINvQ2hHuc1RQVOTDUY63fPkYpYa35q08is1IDPhyh2zPid8kc6MfpZG4XT+pfqhkCe/UnZ19WAD" +
            "IDE/yaLiVMkK12qjYSeQ2KTnaBCkYMxm8LDrdL0jdB4BnCJ")]
        public string br_dev {
            get {
                return ((string)(this["br_dev"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YjmsIRINvQ2Gz05oTXKxDjUY63fPkYpYa35q08is1ICV7X5UszSZN0c6MfpZG4XT+pfqhkCe/UnZ19WAD" +
            "IDE/yaLiVMkK12qjYSeQ2KTnaBCkYMxm8LDrdL0jdB4BnCJ")]
        public string tx_dev {
            get {
                return ((string)(this["tx_dev"]));
            }
        }
    }
}
